# Generated by Django 5.1.1 on 2024-09-30 05:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Порода"
                    ),
                ),
            ],
            options={
                "verbose_name": "Порода",
                "verbose_name_plural": "Породы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Kitten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50, verbose_name="Цвет")),
                (
                    "age",
                    models.PositiveSmallIntegerField(verbose_name="Возраст (месяцев)"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kittens",
                        to="kittens.breed",
                        verbose_name="Порода",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitten_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Котенок",
                "verbose_name_plural": "Котята",
                "ordering": ["age"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "kitten",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_kitten",
                        to="kittens.kitten",
                        verbose_name="Котенок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг",
                "verbose_name_plural": "Рейтинги",
                "ordering": ["-rating"],
            },
        ),
        migrations.AddIndex(
            model_name="kitten",
            index=models.Index(fields=["age"], name="kittens_kit_age_1d1f75_idx"),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["-rating"], name="kittens_rat_rating_3d2f3a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("kitten", "user")},
        ),
    ]
